//==========================================================================
//  ALEPH software suite
//--------------------------------------------------------------------------
//  Copyright (C) Organisation europeenne pour la Recherche nucleaire (CERN)
//  All rights reserved.
//
//  For the licensing terms see OnlineSys/LICENSE.
//
//--------------------------------------------------------------------------
//
//  Author     : Markus Frank
//==========================================================================
#ifndef ALPHA_GEANT3_GEOMETRY_H
#define ALPHA_GEANT3_GEOMETRY_H 1

/// dd4hep include files
#include <DD4hep/Shapes.h>
#include <DD4hep/Volumes.h>
#include <DD4hep/Objects.h>
#include <DD4hep/Detector.h>
#include <DD4hep/DD4hepUnits.h>

#include <TGeoSystemOfUnits.h>
#include <TGeant4SystemOfUnits.h>

/// dd4hep namespace declaration
namespace dd4hep   {

  /// Base class implementing all helpers to import Geant3 geometries
  /**
   *   \author  M.Frank
   *   \version 1.0
   */
  class geant3_geometry  {
  public:

    class MaterialWrapper  {
      Material material;
    public:
      MaterialWrapper(Material m) : material(m) {}
      ~MaterialWrapper() = default;
      MaterialWrapper& add_composite(double Z, double A, double weight);
    };

    struct mixture_entry { double Z, A, fraction; };
    
  protected:

    class units  {
    public:
      constexpr static const double cm     = TGeant4Unit::cm;
      constexpr static const double degree = 1.0 / TGeant4Unit::radian;
    };

  public:
    Detector& description;
    std::map<std::string, Volume>      volumes;
    std::map<int, Rotation3D>          rotations;

    bool debug_materials             { false };
    bool debug_media                 { false };
    bool debug_placements            { false };
    
  public:
    /// Access material to build volumes
    Material get_material(const std::string& name)  const;
                     
    /// Add rotation matrix to build placement transformations
    void     add_rotation( int index, const Rotation3D& rotation );

    /// Add material to geometry inventory
    void     add_material( int index,
                           const std::string& name,
                           double Z, double A,
                           double density, double intlen, double radlen);

    void     add_mixture(  int index,
                           const std::string& name,
                           double Z, double A, double density, double intlen, double radlen,
                           const std::vector<mixture_entry>& mix);

    /// Add volume medium to geometry inventory
    Material add_medium(   int index,
                           const std::string& name,
                           const std::string& material);

    /// Add volume to geometry inventory
    Volume   add_volume(   int index,
                           const std::string& name,
                           const std::string& material,
                           Solid solid);

    /// Add volume medium to geometry inventory
    PlacedVolume add_placement(int index,
                               const std::string& mother,
                               const std::string& volume,
                               int copy_nr,
                               const Position& position,
                               int index_rotation,
                               const std::vector<double>& params);

  public:
    /// Default constructor
    geant3_geometry(Detector& desc);
    
    /// Default destructor
    virtual ~geant3_geometry();

    void construct(const std::string& top_volume);
    
    /// Handle the conversion of the Geant3 materials:
    virtual void handle_materials() = 0;

    /// Handle the conversion of the Geant3 media
    virtual void handle_media() = 0;

    /// Handle the conversion of the Geant3 volumes
    virtual void handle_volumes() = 0;

    /// Handle the conversion of the Geant3 transformation matrices
    virtual void handle_rotations() = 0;
    
    /// Handle the conversion of the Geant3 placements
    virtual void handle_placements() = 0;
  };   // End class geant3_geometry
  
  /// Concrete implementation class to import Geant3 geometries
  /**
   *   The missing entry points are generated by the
   *   analysis of the sniffer output to the Geant3
   *   simulation program 'extract_geometry.py'
   *
   *
   *   \author  M.Frank
   *   \version 1.0
   */
  class geant3_geometry_imp : public geant3_geometry  {
  public:
    /// Default constructor
    geant3_geometry_imp(Detector& desc);
    /// Default destructor
    virtual ~geant3_geometry_imp();
    /// Handle the conversion of the Geant3 materials:
    virtual void handle_materials()   override;
    /// Handle the conversion of the Geant3 media
    virtual void handle_media()       override;
    /// Handle the conversion of the Geant3 transformation matrices
    virtual void handle_rotations()   override;
    /// Handle the conversion of the Geant3 volumes
    virtual void handle_volumes()     override;
    /// Handle the conversion of the Geant3 placements
    virtual void handle_placements()  override;
  };   // End class geant3_geometry_imp
}      // End namespace dd4hep
#endif // ALPHA_GEANT3_GEOMETRY_H
